definitions:
  model.Project:
    enum:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    type: integer
    x-enum-varnames:
    - Cube222
    - Cube333
    - Cube444
    - Cube555
    - Cube666
    - Cube777
    - CubeSk
    - CubePy
    - CubeSq1
    - CubeMinx
    - CubeClock
    - Cube333OH
    - Cube333FM
    - Cube333BF
    - Cube444BF
    - Cube555BF
    - Cube333MBF
    - JuBaoHaoHao
    - OtherCola
  result.CreateContestRequest:
    properties:
      Description:
        type: string
      EndTime:
        type: integer
      Name:
        type: string
      Rounds:
        items:
          $ref: '#/definitions/result.CreateContestRequestRound'
        type: array
      StartTime:
        type: integer
    type: object
  result.CreateContestRequestRound:
    properties:
      Final:
        type: boolean
      Name:
        type: string
      Number:
        type: integer
      Project:
        $ref: '#/definitions/model.Project'
      Upsets:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /api/contests:
    post:
      parameters:
      - description: Name
        in: body
        name: Name
        required: true
        schema:
          type: string
      - description: Description
        in: body
        name: Description
        required: true
        schema:
          type: string
      - description: Rounds
        in: body
        name: Rounds
        required: true
        schema:
          items:
            $ref: '#/definitions/result.CreateContestRequestRound'
          type: array
      - description: StartTime
        in: body
        name: StartTime
        required: true
        schema:
          type: integer
      - description: EndTime
        in: body
        name: EndTime
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.CreateContestRequest'
      summary: 创建比赛
swagger: "2.0"
